#!/usr/bin/python3.8
import os
import sys


print('2nd argument')
print(sys.argv[1])
message = str(sys.argv[1])
branch = str(sys.argv[2])



def commit(m,b):
    os.system('git add .')
    print('success add')
    os.system('git commit -m "' + m + ' "  ')
    print('success commit')
    status= os.system('git push -u origin '+b)
    print('success push')
    print('commit and push done ')

    print("status = "+status)
commit(message,branch)



