#!/usr/bin/python3.8
import os
import sys
import requests

mUrl = "https://discord.com/api/webhooks/985626234794942515/7UZbJ-czKuBDr_cAikS73-7byp79CocBdFHJUgcKKTPf18fKK23KrbeKm3zOP_Qpu_9f"





print('2nd argument')
print(sys.argv[1])
message = str(sys.argv[1])
branch = str(sys.argv[2])



def commit(m,b):
    succ = 0
    status= os.system('git add .')
    if (status ==0) :
        print('success add')
        succ +=1
        print(succ)
    status = os.system('git commit -m "' + m + ' "  ')
    if (status ==0) :
        print('success commit')
        succ +=1
        print(succ)

    status= os.system('git push -u origin '+b)
    if (status == 0) :
        print('success push')
        print('commit and push done ')
        succ +=1
        print(succ)


    return succ


succ = commit(message,branch)
print("succ" + str(succ))
if succ ==3:
    rep = {"content": "Push success to branch " + branch + "."}
    response = requests.post(mUrl,rep )
    print(response.status_code)






