#!/usr/bin/python3.8
import os
import sys
import requests
from dotenv import load_dotenv
load_dotenv()
mUrl =os.getenv('web_hook')

message = str(sys.argv[1])
branch = str(sys.argv[2])

def commit(m,b):
    succ = 0
    status= os.system('git add .')
    if (status ==0) :
        print('success add \n')
        print('*****************************')
        succ +=1

    status = os.system('git commit -m "' + m + ' "  ')
    if (status ==0) :
        print('success commit \n')
        print('*****************************')
        succ +=1


    status= os.system('git push -u origin '+b)
    if (status == 0) :
        print('success push')
        print('commit and push done ')
        print('*****************************')
        succ +=1

    return succ
succ = commit(message,branch)

if succ ==3:
    rep = {"content": "Push success to branch " + branch + "."}
    response = requests.post(mUrl,rep )
    print(response.status_code)






